### ISSUE TITLE
add command for bootstrapping new projects

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/builder#34] opened 2015-02-10 15:33 UTC
The idea is to do 

```bash
# bootstrap a new cli project
$ builder bootstrap cli --name=new-project --lang=go

# bootstrap a new cli project
$ builder bootstrap web --name=new-project --lang=go
```

**Comment by zeisss** [comment] 2016-03-15 15:07
duplicate of #33

**Closed by zeisss** 2016-03-15 15:07 UTC
Labels: 7 - status/pdv, kind/feature
